# Jekyll blog config file.

# Site settings
# Avilable in templates and HTML files via {{ site.title }}, {{ site.email }},
# and so on.
title: thebelltower blog
email: thebelltower@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by thebelltower.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thebelltower.github.io"
twitter_username:
github_username:  thebelltower

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
